### ISSUE TITLE
Can't nav to localhost:9000

### ISSUE THREAD

**Issue by iksose** [lookfirst/systemjs-seed#2]
For this, or the yeoman generator app. After installing the deps and running `gulp run` the page just hangs

Including my own browser-sync `gulp task` resolves this issue.

**Comment by Hypercubed** [comment]
Same here... had to add:

```
var browserSync = require('browser-sync');
gulp.task('serve', function (done) {
  return browserSync(serverOptions, done);
});
```

**Comment by unoriginalscreenname** [comment]
+1 @Hypercubed .  I commented out the line:

taskMaker.defineTask('browserSync', {taskName: 'serve', config: serverOptions, historyApiFallback: true});

and added in your code below that.

**Comment by Hypercubed** [comment]
Ok, the trouble is with `historyApiFallback: true`.  Remove that (don't set to false) and the browserSync works.

Appears to be fixed recently: https://github.com/lookfirst/gulp-helpers/issues/4

**Comment by unoriginalscreenname** [comment]
+1 again @Hypercubed !

**Comment by unoriginalscreenname** [comment]
Is anybody else having an issue with the server serving the site on first load, but then getting a "Cannot GET /todo" after a refresh or route change?

**Comment by lookfirst** [comment]
Ugh, for some reason I wasn't getting notifications of new issues. I'm looking into this.

**Comment by lookfirst** [comment]
@ericmcgregor I just ran latest of the seed and things are fine for me.

**Comment by Hypercubed** [comment]
@ericmcgregor Some things to check:

What version of gulp-helpers is installed (should be 1.5.5 to avoid issue above)?  Does gulp-helpers have a `node_modules/gulf` folder (it must not).  Did `gulp-ng-html2js` install correctly under gulp-helpers?

I had quite a few problems getting this to run but finally did.  Still can't get `routeBundler` to run though.

**Comment by lookfirst** [comment]
Has this been resolved?

**Comment by unoriginalscreenname** [comment]
I just re-installed this from the repo and it appears to work well.  i believe i may have, as hypercubed noted, been working with a slightly out of date package.

**Comment by lookfirst** [comment]
Ok, closing then. Open a new issue if you need help again! =)
