### ISSUE TITLE
Fails to install due to gulp-ng-html2js in gulp-helpers.

### ISSUE THREAD

**Issue by Hypercubed** [lookfirst/systemjs-seed#3]
So because of this issue (https://github.com/lookfirst/gulp-helpers/issues/6) I could not install or run systemjs-seed.

Here are the very complicated steps to work around:

```
git clone git@github.com:lookfirst/systemjs-seed.git
cd systemjs-seed/
mkdir node_modules/
cd node_modules/
git clone git@github.com:lookfirst/gulp-helpers.git
cd gulp-helpers/
mkdir node_modules/
cd node_modules/
git clone git@github.com:lookfirst/gulp-ng-html2js.git
cd gulp-ng-html2js/
git checkout export2
npm install
cd ../.. # now in gulp-helpers/
# edit package.json to remove gulp-ng-html2js dependency
npm install
cd ../.. # now in systemjs-seed/
npm install
gulp run
```

Finally have systemjs-seed working!

**Comment by Hypercubed** [comment]
Oh, forgot one thing.  I needed to modify the following line in the gulp file:

from:
`var runSequence = gulpHelpers.framework('run-sequence');`

to:
`var runSequence = gulpHelpers.framework('run-sequence').use(gulp);`

This may be a separate issue.

**Comment by lookfirst** [comment]
Sure, but this is a gulp-helpers issue, so let's keep the discussion in one place please. =)

**Comment by Hypercubed** [comment]
Sure, thought it could help others.  The `gulpHelpers.framework('run-sequence').use(gulp)` may be a systemjs-seed issue.

**Comment by Hypercubed** [comment]
The `.use(gulp)` is only needed because of the manual install steps I listed.  Please ignore this.

**Comment by lookfirst** [comment]
Cool. Thanks. =)

**Comment by Hypercubed** [comment]
Tried npm 2.8.3.  Still the same issue.  The error looks something like this:

`npm ERR! git clone C:\Users\username\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lookfirst-gulp-ng-html2js-git-91e2f455 C:\Users\username\.babun\cygwin\tmp\npm-4380-c07b413a\git-cache-09aa2c8126d5\dacb59239da35f691f12631e497b404ba72d8b02: fatal: '/cygdrive/c/Users/username/AppData/Roaming/npm-cache/_git-remotes/https-github-com-lookfirst-gulp-ng-html2js-git-91e2f455/C:\Users\username\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lookfirst-gulp-ng-html2js-git-91e2f455' does not appear to be a git repository`

git and npm are not getting along.

**Comment by lookfirst** [comment]
Thanks for trying the latest version out. 

It might be a good idea to file a bug with npm?

**Comment by Hypercubed** [comment]
I'm hesitant because NPM doesn't officially support Cygwin.  Living with Cygwin is the rebel life!

**Comment by lookfirst** [comment]
At this point, developers living with windows is the rebel life. :stuck_out_tongue_winking_eye:
