### ISSUE TITLE
Gulp test task exits with code 0 with failed tests

### ISSUE THREAD

**Issue by maroshii** [lookfirst/systemjs-seed#7]
``` bash
git clone git@github.com:lookfirst/systemjs-seed.git
cd systemjs-seed
npm install

# make a random test fail.... 

gulp test
if [ $? -eq 0 ]; then echo ok; else echo failed; fi

# > ok
```

I understand that for e2e tests `npm test` should be used instead but shouldn't this task exit with code != 0 anyways?

---

gulpfile:

``` javascript
gulp.task('test', function(callback) {
    return runSequence('recompile', 'karma', function(err) {
        console.error(err); // undefined
        callback(err);
    });
});
```

`err` here should be be defined (right?)

**Comment by lookfirst** [comment]
There is all sorts of issues with this project right now due to code rot (mostly in jspm/systemjs). I'm in the middle of launching a new company so I won't have time to get it up to date for a while. PR's welcome!
